import {FC} from 'react';
import NavBar from '@/components/NavBar/NavBar';
import Head from 'next/head';
import HelpForm from '@/components/HelpForm/HelpForm';
import ShortFooter from '@/components/ShortFooter/ShortFooter';

import styles from '@/styles/LoginHelp.module.scss';

const LoginHelp: FC = () => {
    return (
        <div className={styles.login}>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <title>Netflix</title>
            </Head>
            <NavBar linkLogo showSignButton />
            <main>
                <HelpForm />
                <p>This page is protected by Google reCAPTCHA to ensure you're not a bot. Learn more.</p>
            </main>
            <ShortFooter/>
        </div>
    );
};

export default LoginHelp;
