import { FC } from 'react';
import NavBar from '@/components/NavBar/NavBar';
import Head from 'next/head';
import HelpForm from '@/components/HelpForm/HelpForm';
import ShortFooter from '@/components/ShortFooter/ShortFooter';
import { useLogInState } from '@/hooks/useLogInState';
import BaseButton from '@/components/ui/BaseButton/BaseButton';
import { authOptions } from '../api/auth/[...nextauth]';
import { getServerSession } from 'next-auth';

import styles from '@/styles/LoginHelp.module.scss';

const LoginHelp: FC = () => {
    const loggedIn = useLogInState()

    const logoutHandler = () => sessionStorage.removeItem('newMember')
    return (
        <div className={styles.login}>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <title>Netflix</title>
            </Head>
            <NavBar linkLogo >
                {loggedIn ? <BaseButton text='sign out' linkPath='/' onClick={logoutHandler} /> : <BaseButton text='sign in' linkPath='/login' />}
            </NavBar>
            <main>
                <HelpForm />
                <p>This page is protected by Google reCAPTCHA to ensure you're not a bot. Learn more.</p>
            </main>
            <ShortFooter />
        </div>
    );
};

export default LoginHelp;

export const getServerSideProps = async (context: any) => {
    const token = await getServerSession(
        context.req,
        context.res,
        authOptions
    )
    if (token) return {
        redirect: {
            destination: '/browse',
            permament: false
        }
    }
}